// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBv0VFNm3aiu9NqoUOz7IHaXsky7GgVmZE',
    appId: '1:262089540820:web:cc0114fd5582a241d52741',
    messagingSenderId: '262089540820',
    projectId: 'bookstore-app-223a1',
    authDomain: 'bookstore-app-223a1.firebaseapp.com',
    storageBucket: 'bookstore-app-223a1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwGbWD1L6_jqB8_q1WRodgwimTSyXTs5s',
    appId: '1:262089540820:android:2f8fa93c06acbb12d52741',
    messagingSenderId: '262089540820',
    projectId: 'bookstore-app-223a1',
    storageBucket: 'bookstore-app-223a1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcp7c9Cn-7g5lEEaaFKCR6DoyeZmmteM8',
    appId: '1:262089540820:ios:9b197208518df41dd52741',
    messagingSenderId: '262089540820',
    projectId: 'bookstore-app-223a1',
    storageBucket: 'bookstore-app-223a1.firebasestorage.app',
    iosBundleId: 'com.nazym.bookStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcp7c9Cn-7g5lEEaaFKCR6DoyeZmmteM8',
    appId: '1:262089540820:ios:9b197208518df41dd52741',
    messagingSenderId: '262089540820',
    projectId: 'bookstore-app-223a1',
    storageBucket: 'bookstore-app-223a1.firebasestorage.app',
    iosBundleId: 'com.nazym.bookStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBv0VFNm3aiu9NqoUOz7IHaXsky7GgVmZE',
    appId: '1:262089540820:web:784b1d1e28ba28c8d52741',
    messagingSenderId: '262089540820',
    projectId: 'bookstore-app-223a1',
    authDomain: 'bookstore-app-223a1.firebaseapp.com',
    storageBucket: 'bookstore-app-223a1.firebasestorage.app',
  );
}
